require "type_struct/ext"
require "type_struct/generator"

module GeneratorTest
  def test_parse(t)
    hash = {
      message: 'hello',
      posts: [
        {
          id: 123,
          title: "hi",
          time: 123.456,
          show: true,
        }
      ],
      autor: {
        name: "ksss",
        age: 30,
      },
      links: [],
      friends: {},
    }
    result = TypeStruct::Generator.new.parse("AutoGeneratedStruct", hash)
    expect = <<DEFINITION
Post = TypeStruct.new(
  id: Integer
  title: String,
  time: Float,
  show: TrueClass | FalseClass,
)
Autor = TypeStruct.new(
  name: String,
  age: Integer
)
AutoGeneratedStruct = TypeStruct.new(
  message: String,
  posts: ArrayOf(Post),
  links: Array,
  friends: Hash,
)
DEFINITION
    unless result == expect
      t.error("unexpected result")
    end
  end
end
