class TypeStruct
  # Respects:
  #   http://json2struct.mervine.net/
  #   https://mholt.github.io/json-to-go/
  class Generator
    def initialize
      @io = StringIO.new
    end

    # call-seq:
    #   parse(name, hash) -> String
    #
    # Auto Generate TypeStruct definition from Hash object.
    #
    # require 'type_struct/generator'
    #
    # puts TypeStruct::Generator.new.parse("AutoGeneratedStruct", {hello: 'world!'})
    # # => "AutoGeneratedStruct = TypeStruct.new(\nhello: String,\n)\n"
    #
    # See also type_struct/generator/{json,yaml}.rb
    def parse(name, h)
      io = StringIO.new
      io.puts "#{name} = TypeStruct.new("
      h.each do |key, value|
        case value
        when Array
          if value.empty?
            io.puts "  #{key}: Array,"
          else
            type_struct = key.to_s.gsub(/s\z/, '').split('_').map(&:capitalize).join
            parse(type_struct, value.first)
            io.puts "  #{key}: ArrayOf(#{type_struct}),"
          end
        when Hash
          if value.empty?
            io.puts "  #{key}: Hash,"
          else
            type_struct = key.to_s.gsub(/e?s\z/, '').split('_').map(&:capitalize).join
            parse(type_struct, value)
          end
        when NilClass
          io.puts "  #{key}: Object,"
        when TrueClass, FalseClass
          io.puts "  #{key}: TrueClass | FalseClass,"
        else
          io.puts "  #{key}: #{value.class},"
        end
      end
      io.puts ")"
      @io.print io.string
      @io.string
    end
  end
end
